routes/web.php
<?php

use App\Http\Controllers\ShopController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminOrderController;
use App\Http\Controllers\ApiProvizorController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\KingLigaController;
use App\Http\Controllers\KingSoldBattleController;
use App\Http\Controllers\LoaderController;
use App\Http\Controllers\NewsLikeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OuterMarketController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\ShopOrderController;
use App\Http\Controllers\ShiftController;
use App\Http\Controllers\SoldController;
use App\Http\Controllers\PlanController;
use App\Services\HelperServices;
use PHPUnit\TextUI\Help;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
// Route::get('kingligas', function () {
//     $helper = new HelperServices;
//     try {
//         $helper->kingSoldsCreate();
//         return response()->json("Ok");
//     } catch (\Throwable $th) {
//         return response()->json($th->getMessage());
//     }
// });
Route::get('admin/users', [AdminController::class, 'users'])->name('admin.users');
Route::get('admin/searchUsers', [AdminController::class, 'searchUsers']);


Route::get('test-topshiriq-lms', [AdminController::class, 'TTL'])->name('test-topshiriq-lms');


Route::middleware('auth')->group(function () {

    Route::put('/apteka-edit/{id}',[HomeController::class,'AptekaEdit'])->name('apteka-edit');
    Route::delete('/apteka-delete/{id}',[HomeController::class,'AptekaDelete'])->name('apteka-delete');

    Route::get('/', [HomeController::class, 'index'])->name('home');
    // Route::get('/', [HomeController::class, 'anotherTeacher'])->name('another-teacher');/

    // NEWS SECTION
    Route::get('/allnews', [NewsLikeController::class, 'getAllNews']);
    Route::get('/read-notification/{id}', [NotificationController::class, 'read']);
    Route::get('/all-notification', [NotificationController::class, 'index']);
    Route::get('/read-all', [NotificationController::class, 'readAll']);
    //
    // CRYSTALL
    Route::get('/user-crystall', [UserController::class, 'getUserCrystall']);
    //
    //King liga
    Route::post('/inc-king-liga/{yes}', [KingLigaController::class, 'incKingLiga'])->name('inc-king-liga');
    Route::post('login-user', [UserController::class, 'login'])->name('login-user');
    Route::get('/home', [UserController::class, 'index'])->name('user');
    Route::get('/shopping', [UserController::class, 'shopping'])->name('shopping');

    Route::get('reyting', [UserController::class, 'reyting'])->name('reyting');
    Route::get('my-order', [UserController::class, 'myOrder'])->name('my-order');
    Route::get('my-shop', [UserController::class, 'myShop'])->name('my-shop');

    Route::get('product-shopping/{product_id}', [UserController::class, 'productShopping'])->name('product-shopping');



    Route::resource('shop-product', OuterMarketController::class);
    Route::resource('order', OrderController::class);
    Route::resource('shop-order', ShopOrderController::class);
    Route::resource('admin-order', AdminOrderController::class);

    Route::prefix('admin')->group(function () {
        Route::resource('product', ProductController::class);
        Route::resource('loader', LoaderController::class);

        Route::get('/', [AdminController::class, 'index'])->name('admin');
        Route::post('/order/delivery/{id}', [AdminOrderController::class, 'delivery'])->name('delivery');
        Route::post('/order/cashback/{id}', [AdminOrderController::class, 'cashback'])->name('cashback');
        Route::get('/shop/{id}', [ShopController::class, 'shop'])->name('shop');
    });
    #



    Route::get('shift', [ShiftController::class, 'index'])->name('shift.index');
    Route::post('shift-open', [ShiftController::class, 'open'])->name('shift.open');
    Route::post('shift-close', [ShiftController::class, 'close'])->name('shift.close');

    Route::get('sold', [SoldController::class, 'index'])->name('sold.index');

    Route::post('sold-store', [SoldController::class, 'store'])->name('sold.store');
    Route::post('zakaz-pro', [SoldController::class, 'zakazPro'])->name('zakazPro.store');


    Route::get('sold-check', [SoldController::class, 'check'])->name('sold.check');
    Route::post('king-sold/{id}', [SoldController::class, 'kingSold'])->name('king.sold');

    Route::post('change-image', [ProfilController::class, 'changeImage'])->name('change.image');
    Route::post('change-profil', [ProfilController::class, 'changeProfil'])->name('change.profil');

    Route::post('change-plan', [PlanController::class, 'changePlan'])->name('change.plan');
    Route::get('view-check/{user_id}/{date_begin}/{date_end}', [SoldController::class, 'viewCheck'])->name('view.check');

    Route::post('ksb', [KingSoldBattleController::class, 'ksBattle'])->name('ksb');

    Route::post('ksb-answer', [KingSoldBattleController::class, 'ksBattleAnswer'])->name('answer.ksb');
    Route::post('/first-success', [UserController::class, 'firstSuccess'])->name('first-success');
    Route::post('/first-view', [UserController::class, 'firstViewSuccess'])->name('first-view');
    Route::post('teach-test-store', [UserController::class, 'teachTestStore'])->name('teach-test-store');
    Route::post('teach-test-store-teach', [UserController::class, 'teachTestStoreTeach'])->name('teach-test-store-teach');
    Route::post('teach-test-store2', [UserController::class, 'teachTestStore2'])->name('teach-test-store2');
    Route::post('teach-test-store-teach2', [UserController::class, 'teachTestStoreTeach2'])->name('teach-test-store-teach2');


    Route::post('add-provizor', [UserController::class, 'addProvizor'])->name('add.provizor');
    Route::post('pro-product-save/{user_id}/{order_id}', [ApiProvizorController::class, 'proProductSave'])->name('pro-product.save');




    Route::get('block', function(){
        return view('block');
    })->name('block');

    Route::get('plan/{date}', [PlanController::class, 'getPlans']);

    Route::post('rekrut-check/{id}', [UserController::class, 'rekrutCheck'])->name('rekrut.check');

    Route::post('mijoz-message', [UserController::class, 'mijozMessage'])->name('mijoz.message');



});

Route::post('/user-modal', [UserController::class, 'userModal']);


Route::post('/name-etap', [UserController::class, 'nameEtap'])->name('name-etap');
Route::post('/date-etap', [UserController::class, 'dateEtap'])->name('date-etap');
Route::post('/region-etap', [UserController::class, 'regionEtap'])->name('region-etap');
Route::post('/phone-etap', [UserController::class, 'phoneEtap'])->name('phone-etap');
Route::post('/code-etap', [UserController::class, 'codeEtap'])->name('code-etap');
Route::post('/parol-etap', [UserController::class, 'parolEtap'])->name('parol-etap');
Route::post('/map-etap', [UserController::class, 'mapEtap'])->name('map-etap');

Route::post('/passport-etap', [UserController::class, 'passportEtap'])->name('passport-etap');
Route::post('/photo-etap', [UserController::class, 'photoEtap'])->name('photo-etap');
Route::post('/lavozim-etap', [UserController::class, 'lavozimEtap'])->name('lavozim-etap');

Route::post('provizor', [LoginController::class, 'provizor'])->name('provizor.store');
Route::get('provizor', [UserController::class, 'provizor'])->name('provizor');


// TEST

Route::get('/region-test', function () {
    return view('region-test');
});

resources/views/block.blade.php
@extends('layouts.app')
@section('content')
    
<div class="container h-100 pl-0 pr-0 text-center mt-5 text-white">
   <h2>
        Siz 7 kun ichida planga erisha olamdingiz.Ishga qaytish uchun Regional Menejeringiz bilan gaplashib ko'ring !!!
   </h2>
</div>
@endsection

resources/views/error.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Page Not Found</title>
</head>
<body>
    This is the custom 404 error page.
</body>
</html>

resources/views/index2.blade.php
@extends('layouts.app')
@section('content')

    @include('w-component.smena');

    @include('modals.hisobot')
@endsection

resources/views/market.blade.php
@extends('layouts.app')
@section('content')
    
<div class="overflow-auto">
    @if(Session::has('success_order'))
    <div class="list-group-item session-message" style="border-radius: 15px;">
        <div class="row">
            <div class="col-auto align-self-center">
                <i class="material-icons text-default">check_circle</i>
            </div>
            <div class="col pl-0">
                <div class="row mb-1">
                    <div class="col">
                        <p class="mb-0">{{Session::get('success_order')}}</p>
                    </div>
                    {{-- <div class="col-auto pl-0">
                        <p class="small text-secondary">2/12/2020</p>
                    </div> --}}
                </div>
                {{-- <p class="small text-secondary">{{Session::get('success_order')}}</p> --}}
                <p class="small text-secondary">2/12/2020</p>

            </div>
        </div>
    </div>
    @endif
    <div class="container mb-4 py-3 overflow-auto" >

        <div class="row">
            @isset($products)
                @foreach ($products as $item)
                    <div class="col-6 col-md-4 col-lg-3">
                        <div class="card border-0 mb-4 overflow-hidden">
                            <div class="card-body h-150 position-relative">
                                {{-- <div class="top-right m-2">
                                    <button class="btn btn-sm btn-light btn-rounded btn-40 rounded-circle"><i class="material-icons mt-0 vm">favorite_border</i></button>
                                </div> --}}
                                <div class="bottom-left m-2">
                                    <button class="btn btn-sm btn-default rounded">
                                        {{number_format($item->elexir,0,',',' ')}}
                                        <img src="{{asset('promo/dist/img/promo/eleksir3.png')}}" width="20px" alt="">
                                    </button>

                                </div>
                                <a href="product.html" class="background">
                                    <img src="{{asset('images/'.$item->image)}}" alt="">
                                </a>
                            </div>
                            <div class="card-body ">
                                {{-- <p class="mb-0"><small class="text-secondary">Rockstar</small></p> --}}
                                <a href="product.html">
                                    <p class="mb-0">{{$item->name}}</p>
                                </a>
                                {{-- <h5 class="mb-0">
                                    {{$item->elexir}}
                                        <img src="{{asset('promo/dist/img/promo/eleksir3.png')}}" width="20px" alt="">
                                </h5> --}}
                                {{-- <div>
                                    <button type="button" onclick="plus({{$item->id}})" class="btn btn-sm btn-primary">+</button>
                                </div> --}}
                                <div class="mt-1 text-center">
                                    @if (Auth::user()->cashback >= $item->elexir )
                                        <a href="{{route('product-shopping',$item->id)}}" type="button" class="btn btn-sm btn-primary">Sotib olish</a>
                                    @else
                                        <button type="button" class="btn btn-sm btn-danger">Sotib ololmaysiz eleksir kam</button>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            @endisset
        </div>
    </div>
</div>
@endsection

resources/views/order.blade.php
@extends('layouts.app')
@section('content')
    
<div class="main-container overflow-auto product-margin">

    <div class="container bg-default-light mb-4 py-3 overflow-auto" >
        
        <div class="row">
            <form action="{{route('order.store')}}" method="POST" style="display: contents !important;" id="myForm">
                @csrf
            @foreach ($products as $item)
            
            <div class="col-6 col-md-4 col-lg-3">
                <div class="card border-0 mb-4 overflow-hidden">
                    <div class="card-body h-150 position-relative">
                        <div class="bottom-left m-2">
                            <button type="button" class="btn btn-sm btn-default rounded">Bonus: <span class="product-bonus{{$item->id}}">{{number_format($item->bonus,0,',',' ')}}</span></button>
                        </div>
                        <figure class="background">
                            <img src="{{asset('images/'.$item->image)}}" alt="">
                        </figure>
                    </div>
                    <div class="card-body ">
                        {{-- <p class="mb-0"><small class="text-secondary">Rockstar</small></p> --}}
                        <a href="product.html">
                            <p class="mb-0">{{$item->name}}</p>
                        </a>
                        <a href="product.html">
                            <p class="mb-0"><span class="product-price{{$item->id}}">{{number_format($item->price,0,',',' ')}}</span></p>
                        </a>
                        <div class="container">

                        <div class="btn-group mb-2" role="group" aria-label="Basic example">
                            <button type="button" onclick="minus({{$item->id}})" class="btn btn-sm btn-danger">-</button>
                            <input type="number" name="{{$item->id}}" value="0" class="form-control product{{$item->id}}" style="border-radius: 0px;">

                            {{-- <button type="button" class="product{{$item->id}} btn btn-sm btn-secondary">0</button> --}}
                            <button type="button" onclick="plus({{$item->id}})" class="btn btn-sm btn-primary">+</button>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </form>


        </div>

    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        $("#submitBtn").click(function(){        
            $("#myForm").submit(); // Submit the form
        });
    });
    function number_format(number, decimals, dec_point, thousands_sep) {
        number = number.toFixed(decimals);

        var nstr = number.toString();
        nstr += '';
        x = nstr.split('.');
        x1 = x[0];
        x2 = x.length > 1 ? dec_point + x[1] : '';
        var rgx = /(\d+)(\d{3})/;

        while (rgx.test(x1))
            x1 = x1.replace(rgx, '$1' + thousands_sep + '$2');

        return x1 + x2;
    }
    function minus($id)
    {
        var stock = parseInt($(`.product${$id}`).val());
        if(stock != 0)
        {
            $(`.product${$id}`).val(stock-1);
            var price = parseInt($(`.product-price${$id}`).text().replace(/[^0-9]/g,''));
            var bonus = parseInt($(`.product-bonus${$id}`).text().replace(/[^0-9]/g,''));

            var orderPrice = parseInt($('.summa-header').text().replace(/[^0-9]/g,''));
            var orderBonus = parseInt($('.bonus-header').text().replace(/[^0-9]/g,''));

            var allprice = number_format(orderPrice-price, 0, ',', ' ');
            var allbonus = number_format(orderBonus-bonus, 0, ',', ' ');

            $('.order-header').css('display','');
            $('.summa-header').text(allprice);
            $('.bonus-header').text(allbonus);
            var orderPrice = parseInt($('.summa-header').text());
            if(orderPrice == 0)
            {
                $('.order-header').css('display','none');
                $('.product-margin').css('margin-top','0%');
            }
        }
        
    }
    function plus($id)
    {
        var stock = parseInt($(`.product${$id}`).val());
        $(`.product${$id}`).val(stock+1);
        var price = parseInt($(`.product-price${$id}`).text().replace(/[^0-9]/g,''));
        var bonus = parseInt($(`.product-bonus${$id}`).text().replace(/[^0-9]/g,''));

        var orderPrice = parseInt($('.summa-header').text().replace(/[^0-9]/g,''));
        var orderBonus = parseInt($('.bonus-header').text().replace(/[^0-9]/g,''));

        var allprice = number_format(price+orderPrice, 0, ',', ' ');
        var allbonus = number_format(bonus+orderBonus, 0, ',', ' ');

        $('.order-header').css('display','');
        $('.product-margin').css('margin-top','35%');
        $('.summa-header').text(allprice);
        $('.bonus-header').text(allbonus);
    }
</script>
@endsection

resources/views/region-test.blade.php
@extends('layouts.app')
@section('content')
<div class="modal-dialog modal-dialog-scrollable" role="document" 
    style="position: absolute;left:0;top:0;z-index:10000">
    <livewire:plan>
</div>
@endsection

resources/views/reyting.blade.php
@extends('layouts.app')
@section('content')
    
<div class="main-container overflow-auto">

    <div class="container mb-4">
        <div class="card">
            <div class="card-header border-bottom">
                <h6 class="mb-0 text-center">Provizorlar Reytingi</h6>
            </div>
            <div class="card-body px-0 pt-0">
                <ul class="list-group list-group-flush">
                    @isset($users)
                        @foreach($users as $key => $item)
                            <li class="list-group-item">
                                <div class="row align-items-center">
                                    <div class="col-auto">
                                        <div>
                                            {{$key+1}}
                                        </div>
                                    </div>
                                    <div class="col-auto pr-0 pl-0">
                                        <div class="avatar avatar-40 rounded">
                                            
                                            <div class="background">
                                                <img src="https://api.multiavatar.com/kathrin.svg" alt="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col align-self-center pr-0">
                                        <h6 class="font-weight-normal mb-1">{{$item->last_name}} {{$item->first_name}}</h6>
                                        <p class="small text-secondary">{{$item->pharmacy}}</p>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-success">
                                            {{$item->cashback}}
                                            <img src="{{asset('promo/dist/img/promo/eleksir3.png')}}" width="20px" alt="">
                                        </h6>
                                    </div>
                                </div>
                            </li>
                        @endforeach
                    @endisset
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ts.blade.php
@extends('layouts.app')
@section('content')
    <livewire:profile>
@endsection